version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "9090:80"
      volumes:
          - ./app:/var/app
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=contest"
  db:
      image: mysql
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=contest
      volumes:
          - ./database:/var/lib/mysql
